---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # Rancher expects the node driver binary to be in the format
    # docker-machine-driver-*.
    binary: docker-machine-driver-oxide
    flags:
      - -trimpath
    ldflags:
      - "-s -w -extldflags '-static -Wl,--fatal-warnings'"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"

changelog:
  disable: true
