= Oxide Rancher Machine Driver

This repository contains the Oxide Rancher machine driver, also known as a node
driver in Rancher parlance. Rancher uses this node driver to provision virtual
machines on Oxide that can then be used to deploy Kubernetes clusters.

== Build

Build the binary using `+make+`.

[source,sh]
----
make
----

== Deployment

Upload the built binary somewhere accessible from Rancher. The binary name must
match the format `+docker-machine-driver-*+` (e.g.,
`+docker-machine-driver-oxide+`) otherwise Rancher will error when trying to
activate the node driver.

Ensure your `+kubectl+` context is configured to use your Rancher Kubernetes
cluster.

Create the following Kubernetes manifest.

.oxide-nodedriver.yaml
[source,yaml]
----
---
apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  name: oxide
  annotations:
    privateCredentialFields: token
    publicCredentialFields: host
  finalizers:
  - controller.cattle.io/node-driver-controller
spec:
  active: true
  addCloudCredential: true
  builtin: false
  checksum: <SHA256SUM_OF_BINARY>
  description: "Oxide Rancher node driver."
  displayName: oxide
  externalId: ""
  uiUrl: ""
  url: "https://example.com/docker-machine-driver-oxide"
----

Apply the Kubernetes manifest to create the Oxide Rancher node driver.

[source,sh]
----
kubectl apply -f oxide-nodedriver.yaml
----

== Releasing

This project uses https://goreleaser.com/[GoReleaser] to build binaries and
create GitHub releases. The release process is as follows.

. Determine the version to be released. This could be a new major version or a
minor or patch version (e.g., `+v1.0.0+`).

. Determine the version control revision to be released (e.g., `+1a0acaf+`).
Usually this is the latest revision on the default branch for major version
releases but it could be another revision for minor or patch releases.

. Create a Git tag on the version control revision with a name that matches the
version to be released (e.g., `+git tag -a v1.0.0 1a0acaf+`).

. Push the newly created Git tag to GitHub (e.g., `+git push origin v1.0.0+`).

. Monitor the latest
https://github.com/oxidecomputer/rancher-machine-driver-oxide/actions/workflows/release.yaml[Release]
GitHub Actions job to ensure it runs successfully.

. Ensure the
https://github.com/oxidecomputer/rancher-machine-driver-oxide/releases[GitHub Releases]
page shows a new release for the desired version.

.. Update the description for the release as necessary.

.. Ensure the release is published, not a draft.
